[package]
name = "nari2d_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde_impl"]
serde_impl = ["serde", "spade/serde_serialize", "serde_derive", "nalgebra/serde-serialize"]

[dependencies]
thiserror = "^1.0"
bevy_ecs = "^0.5"
petgraph = "^0.6"
parking_lot = "^0.11"
dashmap = "^4.0"
ahash = "^0.7"
rstar = "^0.9"
cdt = "0.1.0"
delaunator = "1.0.1"
nalgebra = "^0.29"
robust = "^0.2"

[dependencies.image]
version = "^0.23"
default-features = false

[dependencies.spade]
version = "^1.8"

[dependencies.serde]
version = "^1.0"
default-features = false
features = ["rc", "serde_derive"]
optional = true

[dependencies.serde_derive]
version = "^1.0"
optional = true

[dependencies.smallvec]
version = "^1.7"
features = ["serde", "union", "const_generics", "const_new"]

[dependencies.nari2d_traits]
path = "../nari2d_traits"
